site_name: Home Assistant documentation
docs_dir: /homeassistant/documentation
use_directory_urls: False
theme:
  name: material
  logo: assets/mkdocs_icon.png
  features:
    - header.autohide
  include_search_page: false
  search_index_only: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_css:
  - assets/stylesheet.css
extra_javascript:
  - assets/search-shortcut.js
  - assets/page-memory.js
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - toc:
      permalink: "#"
  - plantuml_markdown:
      server: "http://www.plantuml.com/plantuml"
hooks:
  - /etc/mkdocs-addon-static/hooks.py
plugins:
  - search
  - git-revision-date-localized:
      type: timeago
      fallback_to_build_date: true
